In [2]:
import numpy as np

creating

In [2]:
x1 = np.array([1, 2, 3, 4])
print(x1)
print(x1.shape)
print(x1.ndim)
print(type(x1))

[1 2 3 4]
(4,)
1
<class 'numpy.ndarray'>


In [5]:
x2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(x2)
print(x2.shape)
print(x2.ndim)
print(type(x2))

[[1 2 3]
 [4 5 6]]
(2, 3)
2
<class 'numpy.ndarray'>


In [6]:
a = np.arange(10, 50, 10)
print(a)


[10 20 30 40]


In [7]:
b = np.linspace(10, 15, 25)
print(b)

[10.         10.20833333 10.41666667 10.625      10.83333333 11.04166667
 11.25       11.45833333 11.66666667 11.875      12.08333333 12.29166667
 12.5        12.70833333 12.91666667 13.125      13.33333333 13.54166667
 13.75       13.95833333 14.16666667 14.375      14.58333333 14.79166667
 15.        ]


In [13]:
c = np.random.randint(-10, 10, (4, 6))
print(c)

[[ -5 -10   9   9   8  -4]
 [ -9  -2   2   2   0  -3]
 [  1  -8   1   9   8   3]
 [  8  -1   3   5   2  -3]]


In [4]:
# creating array from a iterator

list_b = [1, 2, 3, 4, 5, 6, 7, 8 ,9]

b = np.array(list_b).reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# creating multi-dimension array from a iterator
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [9]:
# dtype can also be specified
c = np.array( [ [1, 2], [3, 4] ], dtype = complex)
print(c)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [11]:
# arra of zeros
zeros = np.zeros( (3, 4) )
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
# array of ones
ones = np.ones(2, 3, 4)
print(ones)

TypeError: Cannot interpret '3' as a data type

In [14]:
a = np.array([20, 30, 40, 50])
print(a)

b = np.arange(4)
print(b)

c= a-b 
print(c)


[20 30 40 50]
[0 1 2 3]
[20 29 38 47]


In [17]:
b** 2 

array([0, 1, 4, 9])

In [18]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [19]:
a>35

array([False, False,  True,  True])

In [23]:
A = np.array( [ [1, 1], [0, 1] ])
B = np.array( [ [2, 0], [3, 4] ])

prod1 = A*B     # elementwise product
print(prod1)

prod2 = A @ B   # matrix product
print(prod2)

prod3 = A.dot(B)    #another matrix product
print(prod3)



[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [24]:
def f(x, y):
    return 10*x+y

In [25]:
print(f(2,4))

24


In [33]:
b = np.fromfunction(f,(5, 4), dtype = int)
b[2,3]

23

In [37]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))

print(a)
print(b)

# stacking vertically
np.vstack((a,b))

[[4. 7.]
 [2. 0.]]
[[3. 9.]
 [4. 8.]]


array([[4., 7.],
       [2., 0.],
       [3., 9.],
       [4., 8.]])

In [38]:
x = np.linspace(10, 99, 100).reshape(10,10).astype(int)
x

array([[10, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [27, 28, 29, 30, 31, 32, 33, 34, 35, 36],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45],
       [45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [54, 55, 56, 57, 58, 59, 60, 61, 62, 63],
       [63, 64, 65, 66, 67, 68, 69, 70, 71, 72],
       [72, 73, 74, 75, 76, 77, 78, 79, 80, 81],
       [81, 82, 83, 84, 85, 86, 87, 88, 89, 90],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

indexing and slicing

In [39]:
print(x[0, 0])  # first element
print(x[-1, -1])  # last element
print(x[5, 7])  # 5 row and 7 column index element
# row
print(x[0]) # first row
print(x[-1]) # last row


10
99
61


In [40]:
print(x[:, 0])  # first column
print(x[:,-1])  # last column

[10 18 27 36 45 54 63 72 81 90]
[18 27 36 45 54 63 72 81 90 99]
