In [2]:
import numpy as np

In [3]:
a = np.array([20,30,40])
b = np.array([40,60,80])
c= np.array([3])
print(a)
print(b)
print(a + b)
print(a*c)

[20 30 40]
[40 60 80]
[ 60  90 120]
[ 60  90 120]


In [4]:
# slicing of array

arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


In [5]:
# slicing of nested array
arr = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
print(arr[0:2, 0:3])    # elements of both array
print(arr[0, 0:3])      # multiple element of 1st child array
print(arr[1, 0:2])     # multiple element of 2nd child array
print(arr[1,2])     # single elemnt of nested array

[[10 20 30]
 [50 60 70]]
[10 20 30]
[50 60]
70


In [6]:
# attributes of array

# shape of aray
arr = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
print(np.shape(arr))    # (rows, columns)
print(np.size(arr))     # no. of elements in array
print(np.ndim(arr))     # no. of dimentions of array
print(arr.dtype)        
print(type(arr))
print(arr.astype(int))


(2, 4)
8
2
int64
<class 'numpy.ndarray'>
[[10 20 30 40]
 [50 60 70 80]]


attributes of array or inspecting an array
- a.shape - Array dimensions (row, columns)
- len(a) - Length of  nested arrays
- b.ndim - Number of array dimensions
- e.size - Number of array elements
- b.dtype - Data type of array elements
- b.astype(int) - Convert on array to a different type

In [7]:
# adding or subtaracting an array

a = np.array([[20, 30, 40], [20, 10, 15]])
b = np.array([[40, 60, 80],[20, 30, 40]])
print("ADD")
print(a + b)
print(np.add(a, b))

print("SUBTRACT")
print(b - a)
print(np.subtract(a,b))


ADD
[[ 60  90 120]
 [ 40  40  55]]
[[ 60  90 120]
 [ 40  40  55]]
SUBTRACT
[[20 30 40]
 [ 0 20 25]]
[[-20 -30 -40]
 [  0 -20 -25]]


In [8]:
# multiply or divide of array

a = np.array([[20, 30, 40], [20, 10, 15]])
b = np.array([[40, 60, 80],[20, 30, 40]])
print("MULTIPLY")
print(a * b)
print(np.multiply(a, b))

print("DIVIDE")
print(b / a)
print(np.divide(a,b))


MULTIPLY
[[ 800 1800 3200]
 [ 400  300  600]]
[[ 800 1800 3200]
 [ 400  300  600]]
DIVIDE
[[2.         2.         2.        ]
 [1.         3.         2.66666667]]
[[0.5        0.5        0.5       ]
 [1.         0.33333333 0.375     ]]


In [9]:
# POWER AND SQUARE ROOT

arr1 = np.array([2, 3, 4, 5])
arr2 = np.array([2])
print("POWER")
print(np.power(arr1, arr2))

arr3 = np.array([4,  9, 16, 25])
print("SQRT")
c = np.sqrt(arr3)
print(c.astype(int))


POWER
[ 4  9 16 25]
SQRT
[2 3 4 5]


combining and spliting array

In [10]:
a = np.array([[20, 30, 40], [20, 10, 15]])
b = np.array([[40, 60, 80],[20, 30, 40]])
print(np.concatenate([a, b]))

[[20 30 40]
 [20 10 15]
 [40 60 80]
 [20 30 40]]


In [11]:
print(np.concatenate([a, b], axis = 1))

[[20 30 40 40 60 80]
 [20 10 15 20 30 40]]


In [12]:
print(np.hstack([a, b]))    # horizontal concat

[[20 30 40 40 60 80]
 [20 10 15 20 30 40]]


In [13]:
print(np.vstack([a, b]))    # vertical concat

[[20 30 40]
 [20 10 15]
 [40 60 80]
 [20 30 40]]


In [14]:
a = np.array ([20, 30, 40, 10, 20, 40])
b = np.array_split(a,3)
print(b)

[array([20, 30]), array([40, 10]), array([20, 40])]


In [15]:
a = np.array ([[20, 30, 40],[10, 20, 40]])
b = np.array_split(a,2)
print(b)

[array([[20, 30, 40]]), array([[10, 20, 40]])]


ADDING AND REMOVING ELEMENTS IN THE ARRAYS
- np.append(h, g) - Append items to an array
- np.insert(a, 1, 5) - Inserts items in an array
- np.delete(a, [1]) - Delete items from an array

In [16]:
a = np.array([20,30, 40, 60])
print(np.append(a, 90))

b = np.array([[20, 40], [30, 50]])
print(np.append(b, [90, 100]))

[20 30 40 60 90]
[ 20  40  30  50  90 100]


In [17]:
a = np.array([20,30, 40, 60])
print(np.insert(a,1,2))  #array, index, value

b = np.array([[20, 40], [30, 50]])
print(np.insert(b,0, [5, 10], axis = 1))

print(np.insert(b, [1,2], [6,4], axis =0))

[20  2 30 40 60]
[[ 5 20 40]
 [10 30 50]]
[[20 40]
 [ 6  4]
 [30 50]
 [ 6  4]]


In [18]:
print(a)
print(np.delete(a,1))
print(np.delete(a,1))

[20 30 40 60]
[20 40 60]
[20 40 60]


SORT, FILTER, SEARCH

In [19]:
ar = np.array([7,5, 4, 8, 2, 9])
print(np.sort(ar))
ar1 = np.array([[6, 11, 9, 3, 4, 5], [7, 5, 4, 8, 2, 9]])
print(np.sort(ar1))

[2 4 5 7 8 9]
[[ 3  4  5  6  9 11]
 [ 2  4  5  7  8  9]]


In [20]:
ar = np.array([7, 5, 4, 8, 2, 9])
s = np.where(ar % 2 == 0)    # gives index of that element
print(s)

ar1 = np.array([1, 2, 3, 4, 5])
ss = np.searchsorted(ar1, 4)    # it search the element of already sorted array
print(ss)


(array([2, 3, 4]),)
3


In [21]:
ar = np.array([10, 40, 30, 20])
fa = [True, False, False, True]
print(ar[fa])   # both ar and fa has same no of elements 
fa1 = ar > 25
print(ar[fa1])

[10 20]
[40 30]


AGGREGATING FUNCTIONS

In [22]:
a = np.array([10, 40, 30, 20])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.cumsum(a))
print(np.cumprod(a))

100
10
40
4
[ 10  50  80 100]
[    10    400  12000 240000]


In [38]:
a = [10, 20, 30, 40]
b = [3, 5, 2, 5]

price = np.array(a)
quant = np.array(b)

print( price, "\n", quant)

c = np.cumprod([price, quant], axis = 0)
d = c[1]
print("product",d)
print("total",np.sum(d))

[10 20 30 40] 
 [3 5 2 5]
product [ 30 100  60 200]
total 390


STATISTICAL FUNCTIONS UNDER NUMPY

In [43]:
#import satistics as stats for mode
a1 = np.array([200, 300, 150, 130, 200])
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

196.0
200.0
58.855755878248644
3464.0


In [44]:
# coefficient
# -1 repreesent inversely proportional relation ship
# 1 represents proportional relation ship
# 0 means no relationship
tobacoo_consumption = np.array([30, 50, 10, 30, 50, 40])
deaths = np.array([100, 120, 70, 100, 120, 112])
print(np.corrcoef([tobacoo_consumption, deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [45]:
price = np.array([300, 100, 350, 150, 200])
sales = np.array([10, 20, 7, 17, 3])

print(np.corrcoef([price, sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
